# Generated by Django 4.1.1 on 2022-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_contest', models.BooleanField(default=False)),
                ('is_event', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
