# Generated by Django 4.1.1 on 2022-09-07 12:51

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(verbose_name='Məzmun'),
        ),
    ]
